name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.7.2
  dartz: ^0.10.1
  sqflite: ^2.4.1
  get_it: ^8.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/notes.png"

flutter:
  uses-material-design: true
  assets:
    - lib/core/localization/languages/
    - assets/
